      REAL*8       XMRAD,XRAD,XMRAD0,
     1		   ROA,ROB,ROC,ROD,ROG,
     2             ROSG,ROSH,ROV,XA,XB,XC,XD,
     3             XG,XSG,XV,ROICE,
     4             ROA0,ROB0,ROC0,ROD0,ROG0,
     5		   ROICE0,ROSG0,ROV0,XM0
      COMMON/ABUND/XMRAD(IMX,LR),XRAD(IMX,LR),XMRAD0(IMX,LR),
     1		   ROA(IMX),ROB(IMX),ROC(IMX),ROD(IMX),ROG(IMX,LG),
     2             ROSG(IMX,LG),ROV(IMX),XA(IMX),XB(IMX),XC(IMX),
     3             XD(IMX),XG(IMX,LG),XSG(IMX,LG),XV(IMX),ROICE(IMX),
     4             ROA0(IMX),ROB0(IMX),ROC0(IMX),ROD0(IMX),ROG0(IMX,LG),
     5             ROICE0(IMX),ROSG0(IMX,LG),ROV0(IMX),XM0(IMX)

      REAL*8       DQVG1,DQVG2,ROAINT
      COMMON/AMCUB/DQVG1(IMX,LG),DQVG2(IMX,LG),ROAINT(IMX)

      REAL*8       DQGDT,DQVDT,DQVGDT,
     1             QG,QV,QVG
      COMMON/ENERG/DQGDT(IMX,LG),DQVDT(IMX),DQVGDT(IMX,LG),QG(IMX,LG),
     1             QV(IMX),QVG(IMX,LG)

      REAL*8       ERHS,ELHS,SVG,RATFL,PCR,
     1             HOUR
      COMMON/INFOR/ERHS(IMX),ELHS(IMX),SVG(IMX),RATFL(IMX),PCR(IMX),
     1             HOUR(IMX)

      REAL*8       DGFDTL,DGFDTR,
     1             DQV1,DQV2,DVFDTL,DVFDTR,PO,
     2             GAFL,VAFL,XMFL,VFL,
     3             VFR,GFL,GFR,TET,ALFP
      COMMON/KNUFL/DGFDTL(IMX,LG),DGFDTR(IMX,LG),
     1             DQV1(IMX),DQV2(IMX),DVFDTL(IMX),DVFDTR(IMX),PO(IMX),
     2             GAFL(IMX,LG),VAFL(IMX),XMFL(IMX),VFL(IMX),
     3             VFR(IMX),GFL(IMX,LG),GFR(IMX,LG),TET(IMX),ALFP(IMX)

      REAL*8       COND,DCONDT,DFLL,DFLR,PSOL,
     1             DM,DM0,DSDT,DUDT,DV,RE,
     2             ETA,FACR,FL,FSQ,P,R,
     3             RHO,RHO0,S,T,T0,TX,
     4             U,U0,XTP,ZGI,ZKN
      COMMON/VECTO/COND(IMX),DCONDT(IMX),DFLL(IMX),DFLR(IMX),PSOL(IMX),
     1             DM(IMX),DM0(IMX),DSDT(IMX),DUDT(IMX),DV(IMX),RE(IMX),
     2             ETA(IMX),FACR(IMX),FL(IMX),FSQ(IMX),P(IMX),R(IMX),
     3             RHO(IMX),RHO0(IMX),S(IMX),T(IMX),T0(IMX),TX(IMX),
     4             U(IMX),U0(IMX),XTP(IMX),ZGI(IMX,LG),ZKN(IMX)

      REAL*8       AG,AGB,AMG,CG,DIAMG,EXPTG,
     1             HSUBG,PZEROG,RHOSOL,SQG,VGFL,
     2             VGFLA,ROSGI,ZG,TSUB,TAUR,HRAD		 
      COMMON/COMPO/AG(LG),AGB(LG),AMG(LG),CG(LG),DIAMG(LG),EXPTG(LG),
     1             HSUBG(LG),PZEROG(LG),RHOSOL(LG),SQG(LG),VGFL(LG),
     2             VGFLA(LG),ROSGI(LG),ZG(LG),TSUB(LG),TAUR(LR),HRAD(LR)

      REAL*8       ACON,ACONP,ADMAX,AI,ALFA,AIB,AMICE,BDUST,DH2O,PSICON,
     1             ANGLE,AXIS,BETA,BOLK,CD,CONDD,CV,CW,DELMAX,DELMT,DFI,
     2             DFIMAX,DIST,DMTOT,DTIME,DTMAX,ECCEN,EMIS,EPSTIM,
     3             EPSX1,EPSX2,EXPT,FAC,FACTIM,FI,FMTOT,FMTOT0,DVS,
     4		   PROT,GM,PQV,PFL,PXMFL,PAT,VAFLIP,DVFIPL,ACOVAM,HSUB,
     5             PD,PI,PI4,PI43,PICE,PRECX,PZERO,TMELT,HMELT,EXMELT,
     6             CONDW,Q,QVTOT,RDI,RGAS,RHOICE,RHODUS,SFLUX,SIG,SQV,
     7             STOT,TETA,TETAB,TIME,TIME0,TIMEFIN,TNS,TSUBV,
     8             UTOT0,VAPFL,VAPFLA,VMTOT0,XPCR,ZGAS,
     9             FSUR,TML,DECLIN,ALAT,JANGLE,ALFPS,XPS,RO0,PK,EFRAD
      COMMON/PARA1/ACON,ACONP,ADMAX,AI,ALFA,AIB,AMICE,BDUST,DH2O,PSICON,
     1             ANGLE,AXIS,BETA,BOLK,CD,CONDD,CV,CW,DELMAX,DELMT,DFI,
     2             DFIMAX,DIST,DMTOT,DTIME,DTMAX,ECCEN,EMIS,EPSTIM,
     3             EPSX1,EPSX2,EXPT,FAC,FACTIM,FI,FMTOT,FMTOT0,DVS,
     4		   PROT,GM,PQV,PFL,PXMFL,PAT,VAFLIP,DVFIPL,ACOVAM,HSUB,
     5             PD,PI,PI4,PI43,PICE,PRECX,PZERO,TMELT,HMELT,EXMELT,
     6             CONDW,Q,QVTOT,RDI,RGAS,RHOICE,RHODUS,SFLUX,SIG,SQV,
     7             STOT,TETA,TETAB,TIME,TIME0,TIMEFIN,TNS,TSUBV,
     8             UTOT0,VAPFL,VAPFLA,VMTOT0,XPCR,ZGAS,
     9             FSUR,TML,DECLIN,ALAT,JANGLE,ALFPS,XPS,RO0,PK,EFRAD

      REAL*8       HERTZF,PORCOL,POREXP,RO0FAC,ZAC,CLIMIT,EPSHY,
     1             ONEAU,YEAR,TIMIN,TIMAX,SLM,
     2             HAMC,ATAU,EXPTAU,TMIN,TZERO,
     3             ENTOTDI,THICK,DDI,DELTDI,KENRAT,CRDIAM,ENPART,
     4             FIMPACT
      COMMON/PARA2/HERTZF,PORCOL,POREXP,RO0FAC,ZAC,CLIMIT,EPSHY,
     1             ONEAU,YEAR,TIMIN,TIMAX,SLM,
     2             HAMC,ATAU,EXPTAU,TMIN,TZERO,
     3             ENTOTDI,THICK,DDI,DELTDI,KENRAT,CRDIAM,ENPART,
     4             FIMPACT

      INTEGER      JOBNAM,IBG, 
     1		   IAC,IB,IJOB,IMAXP1,ITABLE,NDEX,KMAX,KN,KP,LMAX,
     2             JMAX,MMAX,NMODEL,RUNM,NORB,HANGN,NPRINT,NSAVE,NSTEP,
     3             NTIMAX,NTIME,ORBFIN,ITMODE,NTDAY,IOP,ICORR,ICLAT,
     4             IHYDRO,EOSF,IZONE1,IZONE2,IIMPAC,NDI
      COMMON/INTEG/JOBNAM(12),IBG(LG), 
     1		   IAC,IB,IJOB,IMAXP1,ITABLE,NDEX,KMAX,KN,KP,LMAX,
     2             JMAX,MMAX,NMODEL,RUNM,NORB,HANGN,NPRINT,NSAVE,NSTEP,
     3             NTIMAX,NTIME,ORBFIN,ITMODE,NTDAY,IOP,ICORR,ICLAT,
     4             IHYDRO,EOSF,IZONE1,IZONE2,IIMPAC,NDI
